apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend
          image: us-docker.pkg.dev/comics-350704/docker/frontend:latest
          imagePullPolicy: Always
      restartPolicy: Always
