/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-1",
  aws_cognito_identity_pool_id: "us-west-1:faaaf9e1-5e99-4385-99f4-9b680864e666",
  aws_cognito_region: "us-west-1",
  aws_user_pools_id: "us-west-1_DgGGKT9TS",
  aws_user_pools_web_client_id: "41j9prah66ms4oq8cnv09p4pvq",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_user_files_s3_bucket: "comicss3bucket100929-dev",
  aws_user_files_s3_bucket_region: "us-west-1",
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_user_files_s3_bucket: "comicss3bucket100929-dev",
  aws_user_files_s3_bucket_region: "us-west-1",
  aws_cloud_logic_custom: [
    {
      name: "comicsapi",
      endpoint: "https://utk1bmixg3.execute-api.us-west-1.amazonaws.com/dev",
      region: "us-west-1",
    },
  ],
}

module.exports = awsmobile
