name: Deploy Backend

on:
  workflow_dispatch:
    inputs:
      configure-eks:
        type: boolean
        default: true

      publish-ecr:
        type: boolean
        default: true

      use-cache:
        type: boolean
        default: true

# TODO(enricozb): checkout contexts, see if these have to be env vars
env:
  ECR_REGISTRY_HOST: 566886264221.dkr.ecr.us-east-1.amazonaws.com
  EKS_CLUSTER_NAME: prod-cluster
  EKS_REGION: us-east-1
  GHA_DOCKER_CONTEXT: ./backend/
  GHA_DOCKER_IMAGE_NAME: backend
  GHA_DOCKERFILE: ./deploy/docker/backend.Dockerfile
  K8S_WORKING_DIR: ./deploy/k8s/

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - if: github.event.inputs.publish-ecr
        uses: ./.github/actions/publish-ecr
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          context: ${{ env.GHA_DOCKER_CONTEXT }}
          dockerfile: ${{ env.GHA_DOCKERFILE }}
          registry-host: ${{ env.ECR_REGISTRY_HOST }}
          tags: |
            ${{ env.ECR_REGISTRY_HOST }}/${{ env.GHA_DOCKER_IMAGE_NAME }}:${{ github.sha }}
            ${{ env.ECR_REGISTRY_HOST }}/${{ env.GHA_DOCKER_IMAGE_NAME }}:latest
          use-cache: ${{ github.event.inputs.use-cache == 'true' }}

      - if: github.event.inputs.configure-eks
        uses: ./.github/actions/configure-eks
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-region: ${{ env.EKS_REGION }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          cluster-name: ${{ env.EKS_CLUSTER_NAME }}
          run: |
            kubectl apply -f backend/deployment.yaml
            kubectl apply -f backend/service.yaml
            kubectl apply -f ingress.yaml
            kubectl rollout restart deployment backend-deployment
          working-directory: ${{ env.K8S_WORKING_DIR }}
