name: Javascript CI

on:
  push:
    branches:
      - main
      - michael/js-ci
    paths:
      - backend/**
      - frontend/**
      - .github/workflows/js-ci.yaml
      - .github/actions/js-ci/action.yaml
  pull_request:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/js-ci
        with:
          filter-paths: |
            src:
              - backend/**
              - .github/workflows/js-ci.yaml
              - .github/actions/js-ci/action.yaml
          working-directory: ./backend

      - uses: ./.github/actions/js-ci
        with:
          filter-paths: |
            src:
              - frontend/**
              - .github/workflows/js-ci.yaml
              - .github/actions/js-ci/action.yaml
          working-directory: ./frontend
